USE [master]
GO

CREATE DATABASE [ED_Body1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ED_Body1', FILENAME = N'd:\Data\Galaxy\ED_Body1.mdf' , SIZE = 5000MB , MAXSIZE = 8000MB , FILEGROWTH = 50%)
 LOG ON 
( NAME = N'ED_Body1', FILENAME = N'd:\Data\Galaxy\ED_Body1.ldf' , SIZE = 1300MB , MAXSIZE = 2000MB , FILEGROWTH = 20%)


ALTER DATABASE [ED_Body1] SET COMPATIBILITY_LEVEL = 130
GO

ALTER DATABASE [ED_Body1] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [ED_Body1] SET ANSI_NULLS ON 
GO

ALTER DATABASE [ED_Body1] SET ANSI_PADDING ON 
GO

ALTER DATABASE [ED_Body1] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [ED_Body1] SET ARITHABORT ON 
GO

ALTER DATABASE [ED_Body1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ED_Body1] SET AUTO_SHRINK ON
GO

ALTER DATABASE [ED_Body1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ED_Body1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ED_Body1] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [ED_Body1] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [ED_Body1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ED_Body1] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [ED_Body1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ED_Body1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ED_Body1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ED_Body1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ED_Body1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ED_Body1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ED_Body1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ED_Body1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ED_Body1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ED_Body1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ED_Body1] SET  MULTI_USER 
GO

ALTER DATABASE [ED_Body1] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [ED_Body1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ED_Body1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ED_Body1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ED_Body1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ED_Body1] SET QUERY_STORE = OFF
GO

USE [ED_Body1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ED_Body1] SET  READ_WRITE 
GO


